resources:
  - name: {{ .Values.myRepo.myRepoName }}Git
    type: GitRepo
    configuration:
      gitProvider: avinci_github
      path: {{ .Values.myRepo.gitUser }}/{{ .Values.myRepo.myRepoName }}
      branches:
        include: master

  - name: {{ .Values.myRepo.myRepoName }}Img
    type: Image
    configuration:
      registry: bsArt
      sourceRepository: docker-dev-local
      imageName: platform.jfrog-pipelines.com/docker-dev-local/{{ .Values.myRepo.myRepoName }}_app
      imageTag: latest
      autoPull: true

  - name: {{ .Values.myRepo.myRepoName }}DevBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: bsArt

pipelines:
  - name: {{ .Values.myRepo.myRepoName }}Pipeline
    steps:
      - name: {{ .Values.myRepo.myRepoName }}Build
        type: DockerBuild
        configuration:
          nodePool: aws_u20
          affinityGroup: docker_group
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: platform.jfrog-pipelines.com/docker-dev-local/{{ .Values.myRepo.myRepoName }}_app
          dockerImageTag: ${run_number}
          inputResources:
            - name: {{ .Values.myRepo.myRepoName }}Git
          integrations:
              - name: bsArt

        - name: {{ .Values.myRepo.myRepoName }}Push
          type: DockerPush
          configuration:
            nodePool: aws_u20
            affinityGroup: docker_group
            targetRepository: docker-dev-local
            integrations:
              - name: bsArt
            inputSteps:
              - name: {{ .Values.myRepo.myRepoName }}Build
            outputResources:
              - name: {{ .Values.myRepo.myRepoName }}Img

        - name: {{ .Values.myRepo.myRepoName }}Test
          type: Bash
          configuration:
            nodePool: aws_u20
            inputResources:
              - name: {{ .Values.myRepo.myRepoName }}Img
          execution:
            onExecute:
              - echo "run some test automation platform here"

        - name: {{ .Values.myRepo.myRepoName }}PublishBuild
          type: PublishBuildInfo
          configuration:
            nodePool: aws_u20
            inputSteps:
              - name: {{ .Values.myRepo.myRepoName }}Test
            outputResources:
              - name: {{ .Values.myRepo.myRepoName }}DevBuildInfo
